name: AmDeeNewSite
favicon: null
layout_spectrum: 0.9552702840883285
typography_spectrum: 0.06234608218073845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5647262730635703
  lightness: 0.5790421632118523
  saturation: 0.2559242113493383
  rhythmicContrast: 0.7177579279523343
purpose: []
